<script lang="ts">
	import TitleBar from './components/TitleBar.svelte';
	import TextSegment from './components/TextSegment.svelte';
	import CenterBigText from './components/CenterBigText.svelte';
	import TextBox from './components/TextBox.svelte';
	import BottomWindowSegment from './components/BottomWindowSegment.svelte';
	import Toolbar from './components/Toolbar.svelte';
	const testJson = {
		name: 'some note from  faunadb',
		date: '01/01/2022',
		readme: 'IyAgV2hhdCBJIGhhdmUgdHJpZWQNCkkndmUgc3RvcHBlZCB3YXRjaGluZyBwb3JuLiBJJ20gbWFzdHVyYmF0aW5nIG11Y2ggbW9yZSByYXJlbHkuIEkgYmlrZSBldmVyeSBkYXksIEkgbW92ZSBhIGxvdCwgYW5kIEkgc2lnbmVkIHVwIGZvciBhIGd5bS4gSSByZWFkIGJvb2tzIG9uIGhvdyB0byBzdXJ2aXZlLHdoeSB0byBsaXZlLCBhbmQgaG93IHRvIGxpdmUuIGJvb2tzIG9mIEF1c2Nod2l0eiBzdXJ2aXZvcnMsIG1pbGl0YXJ5IHZldGVyYW5zLCBodW50ZXJzLCBhbmQgb3V0ZG9vciBzdXJ2aXZhbGlzdHMuIG9uZSBib29rIGV2ZXJ5IGZvdXIgZGF5cy4NCkkgcGxheSBnYW1lcyBsaWtlIGFsd2F5cywgYW5kIEkgbWFrZSByYW5kb20gZnJpZW5kcyBsaWtlIGFsd2F5cy4gU2luY2UgYSBsb25nIHRpbWUsIEkndmUgYmVlbiBzbWlsaW5nIGF0IHJhbmRvbSBwZW9wbGUgdG8gbWFrZSB0aGVtIGxpa2UgbWUuDQpBbnRpZGVwcmVzc2FudHMgYXJlIHdvcmtpbmcuIFRoZXkncmUgcmVhbGx5IHN0cm9uZy4gSWYgSSBtaXNzIGEgcGlsbCwgYWZ0ZXIgYSBmZXcgaG91cnMsIG15IHdob2xlIG5lcnZvdXMgc3lzdGVtIHJlbWluZHMgbWUgb2YgaXQuIEkgZmVlbCBpdCBpbnNpZGUgbWUgbGlrZSBhbiBlbGVjdHJpYyBzaG9jay4NCg0KDQpJIGhhdmUgdGhlIF8iaG93Il8gdG8gbGl2ZS4gQnV0IEknbSBsYWNraW5nIHRoZSBfIndoeSJfLiBXaGljaCBpcyBob3cgcGVvcGxlIGxvc2UgaG9wZS4gDQoNCg0KSSd2ZSBmaW5hbGx5IHN0b3BwZWQgdGFsa2luZyB0byBteSBtb3RoZXIsIHNvbWV0aGluZyBJIHdhbnRlZCB0byBkbyBmb3IgYSBsb25nIHRpbWUuIEkgZGlkbid0IGRvIGl0IGVhcmxpZXIgYmVjYXVzZSBJIHdhcyBhZnJhaWQgc2hlJ2QgaHVydCBoZXJzZWxmLiBTaGUgd2FzIHJlYWxseSBjbG9zZSB0byBkb2luZyBpdCwgbW9yZSB0aGFuIG9uY2UsICJiZWNhdXNlIG9mIG1lIi4gSSBrbm93IGl0J3MgdHJ1ZS4gQW5kIEkgZGlkbid0IGNhcmUuDQoNCg0KPlNpbmNlIG15IGRhZCBub3cga25vd3Mgb2YgbXkgbW9tJ3Mgc2lja25lc3MsIGhlIHByb2plY3RzIHRoYXQgSSdsbCBiZSBsaWtlIGhlci4gcHN5Y2hvIGxvY2tlZCBpbiBhIG1lbnRhbCBob3NwaXRhbC4gdGhhbmtzLGRhZC4NCg0KIyAgRGVhciBTbGltDQpJIGhhdmUgZm9yIGEgdmVyeSBsb25nIHRpbWUgbm93IGZlbHQgbGlrZSBodXJ0aW5nIG15c2VsZiBhIGxpdHRsZSBiaXQuIHNvbWV0aGluZyAiY29vbCIsIGxpa2UgYSByYXpvciBhY3Jvc3MgdGhlIGZhY2Ugb3IgdGhlIGNoZXN0LiBTaW5jZSB5b3UncmUgY29tZnkgYW5kIGFsd2F5cyBsb25nIGZvciBtb3JlIGNvbWZvcnQsIHlldCB3aGVuIHlvdSBnbyBvdXQgaW4gc3Vydml2YWwgYW5kIHlvdSdyZSBhbGwgZ29vZCwgaXMgaXQgdGhlIHNhbWUgZm9yIHBhaW4/IEhvdyBtdWNoIGNhbiBvbmUgaHVydCBoaW1zZWxmIGJlZm9yZSBpdCBiZWNvbWVzIG5vcm1hbD8NCg0KDQpJIGRvbid0IHNlZSB0aGUgcG9pbnQgaW4gZG9pbmcgdGhpbmdzIEkndmUgZG9uZSBiZWZvcmUuIExpdmluZyBvbiB0aGUgdmVyZ2Ugb2YgZGVhdGggc3RyaXBwZWQgbWUgb2YgbXkgY29tZm9ydGFibGUgbGlmZS4NCg0KDQpJIHJlYWxseSBoYXRlIG15c2VsZuKAlG15IGJvZHksIG15IGxvb2tzLCBteSBpbnRlbGxpZ2VuY2XigJRhbmQgaGF2ZSBoYXRlZCBteXNlbGYgZm9yIGFzIGxvbmcgYXMgSSBjYW4gcmVtZW1iZXIuIEkndmUgdHJlYXRlZCBteXNlbGYgbGlrZSBhIGRldmljZSBvciBhIHRvb2wgdGhhdCB5b3UgdXNlIHVudGlsIGl0IGJyZWFrcy4gWW91J3ZlIGdvdCB0byB0YWtlIGNhcmUgb2YgeW91ciB0b29scyBhcyB3ZWxsLCBidXQgZG8geW91IGtpc3MgeW91ciBoYW1tZXIgZ29vZG5pZ2h0IG9yIGNhbGwgaXQgY3V0ZSBuYW1lcz8NCg0KDQpUaGVyZSdzIGEgY2hhbmNlIG9mIGNoYW5naW5nIG90aGVycy4gYW5kIHRoaXMgcGxhY2UsIHNheSwgbXkgY291bnRyeSwgb3IgYXQgbGVhc3QgYSBjaXR5LiBidXQgaXQncyBhIGhpZ2gtZWZmb3J0IHRhc2suIFNvbWV0aGluZyBJJ2QgbG92ZSB0byBkby4gb25jZSBmb3IgImJldHRlci4iDQoNCg0KIkJldHRlciIgaXMgaW4gcXVvdGVzIGJlY2F1c2UsIG9mIGNvdXJzZSwgaXQncyBteSB2ZXJzaW9uIG9mICJiZXR0ZXIiLiBidXQgaXQgaXMgYSBzdXBlcmlvciB3YXkgdG8gbGl2ZSBmb3Igb3RoZXJzLCBiZWxpZXZlIG1lLiBJIHNlZSB5b3VyIGVuam95bWVudCB3aGVuIEkgZW50ZXJ0YWluIHlvdTsgSSBzZWUgeW91IGZlZWxpbmcgY29tZm9ydGFibGUgd2l0aCBvdGhlcnM7IEkga25vdyBJJ20gbWFraW5nIHlvdXIgZGF5IG9yIHdlZWsuIElmIHlvdSBhcmVuJ3QgYSBjb21wbGV0ZSBkaWNraGVhZCwgeW91J2xsIGJlIHBhcnQgb2YgbXkgZmFtaWx5Lg0KDQoNCkFsdGhvdWdoIGNhbGxpbmcgeW91IG15IGZhbWlseSBpcyBhIGRpc2dyYWNlIHRvIHlvdSwgV2hhdCBJIG1lYW4gaXMsIGEgZmFtaWx5IGlzIHNvbWV0aGluZyBtb3N0IHBlb3BsZSB3b3VsZCBoYXZlIG9uIHRoZWlyIG1pbmQuDQoNCg0KSSBmZWVsIGxpa2UgY3J5aW5nLCBzY3JlYW1pbmcsIGFuZCBiZWF0aW5nIHVwIGEgaG9tZWxlc3MgcGVyc29uLiBJJ3ZlIG1ldCBhbiBBcmdlbnRpbmlhbiBnaXJsIHRoYXQgSSBidWxseSB0byBnZXQgYXQgbGVhc3QgYSBiaXQgb2YgdGhlIHNlbnNhdGlvbiBvZiBsaXZpbmcuDQpEb24ndCBiZSBtYWQ7IGluIHRoaXMgd29ybGQsIGl0J3MgYnVsbHkgb3IgYmUgYnVsbGllZC4NCg0KDQoNCg0KIyAgUmVzaWxpZW5jZQ0KSSdtIHJlc2lsaWVudDsgSSBoYWQgdG8gYmUuIEkgYmVjYW1lIGxpa2UgdGhpcyBieSBiZWluZyBjb25zdGFudGx5IGV4cG9zZWQgdG8gc3RyZXNzZnVsLCBob3BlbGVzcywgYW5kIG5lcnZlLXdyYWNraW5nIHNpdHVhdGlvbnMuIFRoZSBtb3JlIG9mIHRoZW0gSSBlbmR1cmVkLCB0aGUgbGVzcyBJIGZlYXJlZCwgYW5kIHRoZSBtb3JlIEkgd2FudGVkIHRoZW0gdG8gYmUgY3JhemllciwgbW9yZSBkYW5nZXJvdXMsIGFuZCBtb3JlIHN0cmVzc2Z1bC4NCldoZW4gcGFuaWMgb3V0YnJlYWtzIG9jY3VyLCBJJ2xsIHNjcmVhbSBqdXN0IHRvIGNhdXNlIG1vcmUgb2YgdGhlbS4gSSdsbCBwcmV0ZW5kIEknbSBzY2FyZWQgb3IgZG9uJ3Qga25vdyB3aGF0IHRvIGRvIGp1c3QgdG8gc2VlIHlvdSBoYXZlIGEgYnJlYWtkb3duIG9yIGtlZXAgeW91IHBhbnRpbmcuDQoNCg0KTWF5YmUgSSdtIGRvaW5nIHlvdSBhIGZhdm9yLiBIb3cgbWFueSB0aW1lcyB3aWxsIHlvdSBoYXZlIHRvIGxlYXJuIHdoYXQgdG8gZG8gaW4gY2FzZSBzb21ldGhpbmcgbGlrZSB0aGlzIGhhcHBlbnM/DQoNCg0KSSBhbSBub3Qgc3RyZXNzZWQgd2hlbiB0aGVyZSBhcmUgNSBtaW51dGVzIHVudGlsIHRoZSBwbGFuZSBhbmQgdGhlIHNlY3VyaXR5IHBlcnNvbiB0ZWxscyBtZSB0byBnbyBiYWNrIHRvIHRoZSBlbmQgb2YgdGhlIGxpbmUuIEknbSBub3QgcGFuaWNraW5nIHdoZW4gbXkgZGlzYWJsZWQgZnJpZW5kIGZlbGwgZG93biB0aGUgc3RhaXJzLCBibGVkIGV2ZXJ5d2hlcmUsIHRoZW4gdHVybmVkIG91dCBzaGUgaGFzIHRlbmRlbmNpZXMgZm9yIHNlaXp1cmVz4oCUcGVyZmVjdCB0aW1pbmcgZm9yIGRpc2NvdmVyaW5nIGl0IGFuZCBmb3JnZXR0aW5nIHdobyBJIHdhcy4NCkJ1dCByZXNpbGllbmNlIG9ubHkgZ2V0cyB5b3Ugc28gZmFy4oCUcmVhY3Rpbmcgc291bmRseSB0byBoaWdobHkgc3RyZXNzZnVsIHNpdHVhdGlvbnMgZG9lc24ndCBoZWxwIHlvdSB3aXRoIGFueXRoaW5nIGJ1dCB0aG9zZSBzaXR1YXRpb25zLg0KDQoNClRoaXMgd2hvbGUgdGhpbmcsIGhvd2V2ZXIsIGtpbGxzIGxvdHMgb2YgZW1vdGlvbnMgaW4gbWUuIEFtIEkgaW4gYSBiYWQgc2l0dWF0aW9uLCBvciBhcmUganVzdCBteSBzZW5zZXMgdGVsbGluZyBtZSBzb21lIGJ1bGxzaGl0PyBIb3cgZG8gSSBrbm93IGlmIGl0J3MgcmVhbGx5IGRhbmdlcm91cyB0byBodXJ0IG15c2VsZiB1bnRpbCBJIHRyeT8gTm9ib2R5IHNhbmUgd291bGQgZG8gdGhpcywgYnV0IHRoZW4gbm9ib2R5IHNhbmUgd291bGQgc3RheSBjYWxtIGR1cmluZyB0aGUgdGltZXMgSSd2ZSBzdGF5ZWQgY2FsbS4NCg0KDQojICBJJ20gbG9zaW5nIG15IHNhbml0eS4NCg0KDQpXaGlsZSBhbGNvaG9sIGFuZCBvdGhlciBkZXByZXNzYW50cyBoYXZlIGFsbW9zdCBubyBlZmZlY3Qgb24gbXkgbWVudGFsIGhlYWx0aCwgc3RpbXVsYW50cyBhcmUgZGFuZ2Vyb3VzLiBJIGdldCBjYWZmZWluZSBoaWdocyBmb2xsb3dlZCBieSBtYXNzaXZlIGRyb3AtZG93bnMuIExpa2UganVtcC1vZmYtdGhlLWJyaWRnZSBvbmVzLiBJIHNob3VsZCBiZSB3YXkgbW9yZSBjYXJlZnVsIHdpdGggdGhlc2Uu'
	};
	let htmlAll: string = '';
	const headerRegex: RegExp = /(#+ )(.*)/;
	const boldRegex: RegExp = /(\*\*|__)(.*?)\1/g;
	const italicRegex: RegExp = /\_(\S(.*?\S)?)\_/gm;
	const imageRegex: RegExp = /!\[([^\[]+)\]\(([^\)]+)\)/g;

	const isHeader = (line: string): boolean => headerRegex.test(line);
	const isBox = (line: string): boolean => line.startsWith('>');

	export const convertToHtml = (text: string): void => {
		htmlAll = text.split('\n').filter(Boolean).map((line: string): string => {
			return line
				.replaceAll(boldRegex, '<b>$2</b>')
				.replaceAll(italicRegex, '<i>$1</i>')
				.replaceAll(imageRegex, `</br><fieldset style="background-color:#dfdfdf;padding:unset"><img src='$2' style="display:block;margin:auto;max-width:100%"><p style="text-align:center">$1</p></fieldset>`);
		}).join('');
	};
	convertToHtml(atob(testJson.readme));

</script>

<div>
	<div class="window" style="width: auto; margin: 0.5rem; max-width: 40rem">
		<TitleBar text="{testJson.name}" />
		<Toolbar />
		<fieldset>
			{#each htmlAll as line} {#if isHeader(line)}
			<CenterBigText text="{line.substring(3)}" icon="accessibility_two_windows" />
			{:else if isBox(line)}
			<TextBox text="{line.substring(1)}" />
			{:else if line == '* * *' || line == '***'} <BottomWindowSegment textArray={['...']} />
			{:else}
			<TextSegment text="{line}" />
			{/if} {/each}
		</fieldset>
	</div>
</div>

<style>
	fieldset {
		margin: 1rem;
	}

	imagesubtitle {
		background: rgb(0, 128, 128);
		text-align: center;
		color: white;
		display: inline-block;
		/* padding: 0.1rem; */
		padding-left: 0.4rem;
		padding-right: 0.4rem;
		padding-top: 0;
	}
</style>
